blank_issues_enabled: false

contact_links:
  - name: GitHub Discussions
    url: https://github.com/JurisDev-KE/.github/discussions
    about: Please start a discussion for ideas, questions, or proposals before opening an issue where appropriate.
